### ISSUE TITLE
Auto onchange validate

### ISSUE THREAD

**Issue by ITLec** [ITLec/ITLec.JS.Validation#1]
We need to add new option for enabling auto-validate once the onchange event is executed.

**Comment by dina777** [comment]
see this example with onchange validate 
full example in attachment
[work -multi_lang_on change.zip](https://github.com/ITLec/ITLec.JS.Validation/files/1425010/work.-multi_lang_on.change.zip)

**Comment by ITLec** [comment]
Thanks Dina, all credit for you.

I have added a new function to the library  called **itlec_onchange_validate('ControlName');**

So Now to activate the validation for email field, you should add this code inside your control tag:-

onchange="itlec_onchange_validate('mail');".

I have updated the Validation_Test.HTML sample code.
