### ISSUE TITLE
Support multiple languages 

### ISSUE THREAD

**Issue by ITLec** [ITLec/ITLec.JS.Validation#2]
This library must support multiple languages, and depends on the customer language the library should displayed in the same language.

**Comment by dina777** [comment]
This function convert from English to Arabic 
function ready_for_arabic(){
		// rest all page direction by 
		document.getElementById("wrapper").dir="rtl";
		// change language
		document.getElementById("wrapper").lang="ar";
		// direction of labels 
		$("label").addClass("pull-right");
		// values of labels
		document.getElementById('fullname').textContent="الاسم";
		document.getElementById('l-mail').textContent="الميل الالكترونى";
		document.getElementById('l-phone').textContent="التليفون";
		document.getElementById('l-desc').textContent="الوصف";
		// values of placeholder
		document.getElementById("uname").setAttribute("placeholder","ادخل اسمك");
		document.getElementById("phone").setAttribute("placeholder","ادخل هاتفك المحمول");
	    document.getElementById("mail").setAttribute("placeholder","ادخل ميلك الالكنرونى");
		document.getElementById("des").setAttribute("placeholder","ادخل الوصف");
		document.getElementById("submit").innerHTML="ارسال";
		document.getElementById("cancel").innerHTML="الغاء";
	  // messsage in validation
	  	document.getElementById("uname").setAttribute("data-itlec-requiredmsg","ادخل اسمك");
		document.getElementById("uname").setAttribute("data-itlec-minimumlettersmsg","الاسم لابد ان يكون من 10 حروف فاكثر");
	    document.getElementById("uname").setAttribute("data-itlec-regexpmsg"," لابد ان ينكون اسمك من حروف عربية");
		 document.getElementById("uname").setAttribute("data-itlec-regexp","[ء-ي]");
		 // phone
		 document.getElementById("phone").setAttribute("data-itlec-requiredmsg","ادخل هاتفك المحمول");
		 document.getElementById("phone").setAttribute("data-itlec-regexpmsg","لابد ان ينكون هاتفك من ارقام فقط");
		 // mail
		 document.getElementById("mail").setAttribute("data-itlec-requiredmsg","ادخل ميلك الالكنرونى");
		 document.getElementById("mail").setAttribute("data-itlec-regexpmsg","ادخل ميل الكترونى صحيح");
		 // descrition 
		 document.getElementById("des").setAttribute("data-itlec-requiredmsg","ادخل الوصف");
		 document.getElementById("des").setAttribute("data-itlec-regexp","[ء-ي]");
		 document.getElementById("des").setAttribute("data-itlec-regexpmsg"," لابد ان ينكون الوصف من حروف عربية");
		 document.getElementById("des").setAttribute("data-itlec-minimumwordsmsg","لابد ان يتكون الوصف من 10 كلمات فاكثر");
		
   
		}
and then we can put button in the page like this 
  <button type="button" class="btn btn-primary" onclick="ready_for_arabic();">Arabic</button>

Full example
[work -multi_lang.zip](https://github.com/ITLec/ITLec.JS.Validation/files/1419634/work.-multi_lang.zip)
 in attachment.

**Comment by ITLec** [comment]
Very Good example, Excellent Dina.

I believe there are multiple solutions, for example:

1- We can create multiple attributes for each language (data-itlec-requiredmsg-en,  data-itlec-requiredmsg-ar, data-itlec-requiredmsg-fr, .....).
2- We can make the translation available in an external file (json, xml, ....).

3- We can create a new page for each language, this is the easiest solution.

4- Make it as it is, and the developer should set it during the retrieving of the page.  

5- Your mentioned solution is a brilliant solution, but it requires a lot of changes
----------------
From my point of view, the developer can set the message depends on the language grammatically will be the better solution.
